### ISSUE TITLE
如何打开amis编辑器页面呢？

### ISSUE THREAD

**Issue by tensafe** [csx-bill/quick-admin#1]
{
    layout: false,
    path: '/system/schemaeditor/:id',
    name: '页面配置',
    component: './SchemaEditor',
  },

访问：http://localhost:8000/system/schemaeditor/1

返回加载页面白屏；
console中，提示错误：
<img width="631" alt="image" src="https://github.com/csx-bill/quick-admin/assets/7752462/e96ab285-59c1-4ae4-b3dc-3c3a632f0550">

**Comment by tensafe** [comment]
<img width="619" alt="image" src="https://github.com/csx-bill/quick-admin/assets/7752462/dcab1692-ad83-4a40-9dd9-ac3ee717868d">

**Comment by csx-bill** [comment]
系统菜单->版本管理-> 配置

**Comment by csx-bill** [comment]
需要配合后端项目 quick-boot
