### ISSUE TITLE
ajax请求数据已返回，但界面无法显示数据列表

### ISSUE THREAD

**Issue by shenjler** [csx-bill/quick-admin#2]
环境：
node v14.21.3 (npm v9.8.1)

问题描述：
ajax请求数据已返回，但界面无法显示数据列表。
quick-boot使用最新的sql文件。
角色，菜单，用户列表等等所有的amis接口的数据都无法显示。

<img width="1511" alt="image" src="https://github.com/csx-bill/quick-admin/assets/4507904/b97ad260-10aa-461e-a578-27c4cd75d13c">

<img width="623" alt="image" src="https://github.com/csx-bill/quick-admin/assets/4507904/7d7f6630-3e2b-4bcd-b8ae-648ea4d4fd27">

**Comment by csx-bill** [comment]
用这份初始化试试


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csx-bill/quick-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 上午9:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[csx-bill/quick-admin] ajax请求数据已返回，但界面无法显示数据列表 (Issue #2)





 
环境：
 node v14.21.3 (npm v9.8.1)
 
问题描述：
 ajax请求数据已返回，但界面无法显示数据列表。
 quick-boot使用最新的sql文件。

**Comment by shenjler** [comment]
有新的提交吗？这份是指？main分支最新是上周提交的。本地已经是拉取最新的了。

补充：
<img width="1511" alt="image" src="https://github.com/csx-bill/quick-admin/assets/4507904/da23334c-3c77-4ef0-9164-b399802d5c48">

**Comment by csx-bill** [comment]
最新sql 未更新上去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csx-bill/quick-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 上午10:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [csx-bill/quick-admin] ajax请求数据已返回，但界面无法显示数据列表 (Issue #2)





 
有新的提交吗？这份是指？main分支最新是上周提交的。本地已经是拉取最新的了。
 
补充：

**Comment by csx-bill** [comment]
已更新
