### ISSUE TITLE
设计页面无法保存

### ISSUE THREAD

**Issue by shenjler** [csx-bill/quick-admin#3]
问题描述：
在菜单 在线开发 --> 权限配置 --> 页面设计， 跳转到amis页面设计后，设计完后，没有保存schema的按钮。保存到数据库。无法回显schema。

<img width="1477" alt="image" src="https://github.com/csx-bill/quick-admin/assets/4507904/553defd5-ac1d-485e-9240-ba974b6458b4">

<img width="1511" alt="image" src="https://github.com/csx-bill/quick-admin/assets/4507904/f0493016-205f-4a3e-9919-a119dcf01b0c">

**Comment by csx-bill** [comment]
快捷键保存&nbsp; ctrl+s







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csx-bill/quick-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月8日(星期二) 下午5:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[csx-bill/quick-admin] 设计页面无法保存 (Issue #3)





 
问题描述：
 在菜单 在线开发 --&gt; 权限配置 --&gt; 页面设计， 跳转到amis页面设计后，设计完后，没有保存schema的按钮。保存到数据库。无法回显schema。

**Comment by shenjler** [comment]
快捷键保存&nbsp; ctrl+s 是可以保存。

发现另外一个问题，原来无法回显和保存 是因为 请求接口报错了，我用的数据库是MariaDB，应该schema是关键字吧。加上@TableField("`schema`")注解，就没报错了。

<img width="1363" alt="image" src="https://github.com/csx-bill/quick-admin/assets/4507904/add9499d-ef4e-4311-a3c8-8856ced20f41">
